id: 707be3ac-8fc0-4d9b-ab9b-301a447d187a

slug: cacti
description: |
  ## Why monitor Cacti?
  Monitoring Cacti can help optimize network efficiency, plan for future growth, ensure stability, reduce downtimes, and improve overall network management.
  
  ## Comprehensive monitoring quickstart for Cacti 
  Monitoring Cacti will allow you to effectively track server health, network performance, and resource utilization, while utilizing New Relic's application performance monitoring features to gain deep insights into application behavior, transaction traces, and user experience metrics, enabling users to obtain a holistic view of both infrastructure and application performance.

  ## What’s included in this quickstart?
  New Relic Cacti monitoring quickstart provides quality out-of-the-box reporting:
  - Dashboards (login users, apache cpu load, total apache hits etc)
  - Alerts for Cacti (apache cpu load and total apache hits)

summary: |
   Monitor and analyze your Cacti with New Relic.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Ramana Reddy
title: Cacti
documentation:
  - name: Cacti integration documentation
    description: |
      Monitor and instrument your Cacti with New Relic to gain deep insights into your performance.
    url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/cacti-integration/
keywords:
  - Cacti
  - NR1_addData
  - NR1_sys
dataSourceIds:
  - cacti
dashboards:
  - cacti
alertPolicies:
  - cacti