id: dbt-cloud 
displayName: dbt Cloud 
description: |
  Integrates dbt Cloud with New Relic using an Airflow DAG. With our dashboard and alerts, you can easily find problems with dbt Cloud runs and resources (models, seeds, snapshots and tests). Also includes the ability to collect failed test rows from dbt tests run in Snowflake. 
icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: dbt-cloud 
        frameworkConfigId: dbt-cloud 
      requiresAccount: true 
keywords:
  - dbt cloud
  - dbt
documentation:
  - name: Github Repository 
    description: |
      Github repository with the Airflow DAG and related documentation.
    url: >-
      https://github.com/newrelic-experimental/newrelic-dbt-cloud-integration/
