id: 65c93280-3259-4858-bfb5-e9830d440084
slug: nvidia-jetson
description: |
  ## Why monitor your NVIDIA Jetson?
  Monitoring your NVIDIA Jetson device ensures optimal performance and prevents overheating. Tegrastats includes metrics such as CPU and GPU usage, RAM and swap memory utilization, and critical temperature readings (CPU, GPU, and PMIC). Real-time insights help maintain efficiency and extend the device's lifespan.

  ## Comprehensive monitoring quickstart for NVIDIA Jetson
  Integrate your NVIDIA Jetson device with New Relic for real-time performance insights. Capture essential tegrastats like CPU, GPU, RAM, and temperature readings. Use alerts to prevent overheating and optimize resource usage. 

  ## What’s included in the NVIDIA Jetson quickstart?
  New Relic NVIDIA Jetson monitoring quickstart ability to cover quality on out-of-the-box reporting.
  - Dashboards (RAM and EMC usage, largest free block, PMIC and PLL temperature and etc)
  - Alerts (EMC used, GPU temperature and thermal temperature)
  
summary: |
  Our NVIDIA Jetson integration collects and sends data about your tegrastats utility to New Relic, where you can monitor CPU, GPU, RAM, and temperature readings about your NVIDIA Jetson device.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Jyothi Surampudi
title: NVIDIA Jetson
documentation:
  - name: NVIDIA Jetson integration documentation 
    description: |
      Boost the performance monitoring and instrumentation of your NVIDIA Jetson device by integrating with New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nvidia-jetson-integration
keywords:
  - jetson
  - nvidia jetson
  - tegrastats
  - nvidia
  - NR1_addData
  - NR1_sys
dashboards:
  - nvidia-jetson
alertPolicies:
  - nvidia-jetson
dataSourceIds:
  - nvidia-jetson
