# Sets the URL name of the quickstart on public I/O (required)
slug: dbt-cloud-integration 

# Displayed in the UI (required)
title: Dbt Cloud Integration 

# Long-form description of the quickstart (required)
description: |
  Integrates dbt Cloud with New Relic using an Airflow DAG. With our dashboard and alerts, you can easily find problems
  with dbt Cloud runs and resources (models, seeds, snapshots and tests). Also includes the ability to collect dispaly 
  and alert on test rows from dbt tests run in Snowflake. 

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Dbt Cloud integration using an Airflow DAG.
# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Leo Godin 

# Keywords for filtering / searching criteria in the UI
keywords:
  - guided install
  - open source monitoring

dataSourceIds:
  - dbt-cloud  

# Reference to alert policies to be included in this quickstart
alertPolicies:
  - dbt-failed-test-row 
  - dbt-job-failed
  - dbt-resource-failed
  - dbt-test-warning 

# Reference to dashboards to be included in this quickstart
dashboards:
  - dbt-cloud 

# Documentation references
documentation:
  - name: Installation docs
    url:  https://github.com/newrelic-experimental/newrelic-dbt-cloud-integration/
    description: Installation documentation for dbt Cloud observability using an Airflow DAG
  - name: Git repository 
    url: https://github.com/newrelic-experimental/newrelic-dbt-cloud-integration
    description: Git repository for the Airflow DAG and additional documentation

# Content / Design
icon: logo.svg
website: https://www.getdbt.com/ 
