id: nvidia-jetson
displayName: NVIDIA Jetson
description: |
  Boost the performance monitoring and instrumentation of your NVIDIA Jetson device by integrating with New Relic.
icon: logo.png
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nvidia-jetson-integration
keywords:
  - jetson
  - nvidia jetson
  - tegrastats
  - nvidia
 