id: cacti
displayName: Cacti
description: |
  Monitor and analyze your Cacti with New Relic.
icon: logo.png
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/cacti-integration/
keywords:
  - Cacti
  - logs